services:

  # Mandatory
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    networks:
      - inception_mainnet
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - mysql_user_password
      - mysql_root_password
    restart: unless-stopped
    expose:
      - 3306
  
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - WORDPRESS_ADMIN_PASSWORD_FILE=/run/secrets/wordpress_admin_password
      - WORDPRESS_USER_PASSWORD_FILE=/run/secrets/wordpress_user_password
    networks:
      - inception_mainnet
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    secrets:
      - mysql_user_password
      - mysql_root_password
      - wordpress_user_password
      - wordpress_admin_password
    restart: always
    depends_on:
      - mariadb
      - redis
    expose:
      - 9000
  
  nginx:
    container_name: nginx
    env_file:
      - .env
    networks:
      - inception_mainnet
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    secrets:
      - ssl_key
      - ssl_certificate
    restart: always
    depends_on:
      - adminer
      - portfolio
      - wordpress
    ports:
      - "443:443"

  # Bonus
  adminer:
    container_name: adminer
    env_file:
      - .env
    networks:
      - inception_mainnet  
    build:
      context: ./requirements/bonus/adminer
    restart: unless-stopped
  
  ftp:
    container_name: ftp
    env_file:
      - .env
    networks:
      - inception_mainnet  
    build:
      context: ./requirements/bonus/ftp
    volumes:
      - wordpress:/var/www/html
    secrets:
      - ftp_password
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "44444-44454:44444-44454"

  redis:
    container_name: redis
    networks:
      - inception_mainnet  
    build:
      context: ./requirements/bonus/redis
    restart: unless-stopped
    expose:
      - 6379
  
  portfolio:
    container_name: portfolio
    networks:
      - inception_mainnet  
    build:
      context: ./requirements/bonus/portfolio
    restart: unless-stopped
    expose:
      - 8080

networks:
  inception_mainnet:
    driver: bridge

volumes:

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: data/mariadb
      o: bind
  
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: data/wordpress
      o: bind

secrets:

  mysql_user_password:
    file: ../secrets/mysql-user-password
  
  mysql_root_password:
    file: ../secrets/mysql-root-password
    
  wordpress_user_password:
    file: ../secrets/wordpress-user-password
  
  wordpress_admin_password:
    file: ../secrets/wordpress-admin-password

  ftp_password:
    file: ../secrets/ftp-password

  ssl_key:
    file: ../secrets/ssl/nginx-selfsigned.key
  
  ssl_certificate:
    file: ../secrets/ssl/nginx-selfsigned.crt
